name: example
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- aeson
- gds-api
- servant
- servant-server
- uuid-types

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -Wall
- -Werror

library:
  source-dirs: lib
  dependencies:
  - stm
  - unordered-containers
  - uuid

executables:
  example:
    main: Main.hs
    source-dirs: server
    dependencies:
    - example
    - http-types
    - wai-extra
    - warp

  example-test:
    main: Main.hs
    source-dirs: test
    dependencies:
    - example
    - exceptions
    - hspec
    - http-client
    - http-types
    - servant-client
