sudo: false

language: c

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

addons:
  apt:
    packages:
    - libgmp-dev

services: mongodb

script:
- sleep 15 # https://docs.travis-ci.com/user/database-setup/#MongoDB-does-not-immediately-accept-connections
- ./.travis/$MODE.sh

jobs:
  include:
  - env: MODE=lint
  - env: MODE=test
